### ISSUE TITLE
为什么我报了这个错误呢？ValueError: indices.shape[-1] must be <= params.rank, but saw indices shape: [?,101] and params shape: [?,7] for 'crf/cond/GatherNd' (op: 'GatherNd') with input shapes: [?,7], [?,101].

### ISSUE THREAD

**Issue by hongbosen** [jmhIcoding/bilstm-crf#2]
ValueError: indices.shape[-1] must be <= params.rank, but saw indices shape: [?,101] and params shape: [?,7] for 'crf/cond/GatherNd' (op: 'GatherNd') with input shapes: [?,7], [?,101].

**Comment by jmhIcoding** [comment]
你看看是不是版本什么的出错。
另外，git clone后 你需要手动切换到rewrite 分支。

**Comment by hongbosen** [comment]
好的，谢谢
------------------ 原始邮件 ------------------
发件人: "jmhIcoding"<notifications@github.com>;
发送时间: 2019年5月10日(星期五) 上午8:11
收件人: "jmhIcoding/bilstm-crf"<bilstm-crf@noreply.github.com>;
抄送: "kenn.h"<635577842@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [jmhIcoding/bilstm-crf] 为什么我报了这个错误呢？ValueError: indices.shape[-1] must be <= params.rank, but saw indices shape: [?,101] and params shape: [?,7] for 'crf/cond/GatherNd' (op: 'GatherNd') with input shapes: [?,7], [?,101]. (#2)




你看看是不是版本什么的出错。
 另外，git clone后 你需要手动切换到rewrite 分支。

**Comment by justinzuo** [comment]
> ValueError：indices.shape[-1] 必须 <= params.rank，但看到了索引形状：[?,101] 和参数形状：[?,7] 用于 'crf/cond/GatherNd'（操作：'GatherNd' ) 输入形状：[?,7], [?,101]。

logit= tf.reshape(p,shape=[-1,s[1],tag_nums],name='omit_matrix') 改成 logit= tf.reshape(p,shape=[-1,sentence_len,tag_nums],name='omit_matrix')
